"""init_drone_models

Revision ID: 1a2b3c4d5e6f
Revises:
Create Date: 2026-03-10 12:45:00.000000

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2  # CRITICAL: Alembic often forgets this import!

# revision identifiers, used by Alembic.
revision = '1a2b3c4d5e6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Create flight_paths table
    op.create_table('flight_paths',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('filename', sa.String(length=128), nullable=True),
                    sa.Column('trajectory', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326,
                                                                       from_text='ST_GeomFromEWKT', name='geometry'),
                              nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_flight_paths_filename'), 'flight_paths', ['filename'], unique=False)
    op.create_index(op.f('ix_flight_paths_id'), 'flight_paths', ['id'], unique=False)

    # 2. Create processed_jobs table
    op.create_table('processed_jobs',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('flight_path_id', sa.Integer(), nullable=True),
                    sa.Column('processed_at', sa.DateTime(), nullable=True),
                    sa.Column('video_url', sa.String(length=512), nullable=True),
                    sa.Column('status', sa.String(length=512), nullable=True),
                    sa.Column('path_predictor_type', sa.String(length=512), nullable=False),
                    sa.ForeignKeyConstraint(['flight_path_id'], ['flight_paths.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('flight_path_id')
                    )
    op.create_index(op.f('ix_processed_jobs_id'), 'processed_jobs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Drop processed_jobs
    op.drop_index(op.f('ix_processed_jobs_id'), table_name='processed_jobs')
    op.drop_table('processed_jobs')

    # 2. Drop flight_paths
    op.drop_index(op.f('ix_flight_paths_id'), table_name='flight_paths')
    op.drop_index(op.f('ix_flight_paths_filename'), table_name='flight_paths')
    op.drop_table('flight_paths')
    # ### end Alembic commands ###